export const AUTH_SERVICE_UUID = "1010";
export const USERNAME_CHARACTERISTIC_UUID = "1011";
export const PASSWORD_CHARACTERISTIC_UUID = "1012";
export const TOKEN_CHARACTERISTIC_UUID = "1013";
export const RESPONSE_CHARACTERISTIC_UUID = "1014";

export const RUN_SERVICE_UUID = "1020";
export const RUN_CHARACTERISTIC_UUID = "1021";
export const RUN_RESPONSE_CHARACTERISTIC_UUID = "1022";
